export const ROLES = {
  ADMIN: 'ADMIN',
  PROCUREMENT_OFFICER: 'PROCUREMENT_OFFICER',
  MANAGER: 'MANAGER',
  VENDOR_USER: 'VENDOR_USER',
};

export const ALL_ROLES = Object.values(ROLES);

export const BUYER_ROLES = [
  ROLES.ADMIN,
  ROLES.PROCUREMENT_OFFICER,
];

export const INTERNAL_REVIEW_ROLES = [
  ROLES.ADMIN,
  ROLES.PROCUREMENT_OFFICER,
  ROLES.MANAGER,
];
